---
- name: add gpg key
  rpm_key:
    key: https://mackerel.io/file/cert/GPG-KEY-mackerel-v2
- name: add repository
  yum_repository:
    name: mackerel
    description: mackerel-agent
    baseurl: http://yum.mackerel.io/v2/$basearch
    gpgcheck: yes
- name: install mackerel-agent
  yum:
    name: mackerel-agent
- name: install mackerel-agent-plugins
  yum:
    name: mackerel-agent-plugins
  when: mackerel_agent_install_agent_plugins
- name: install mackerel-check-plugins
  yum:
    name: mackerel-check-plugins
  when: mackerel_agent_install_check_plugins
- name: create mackerel-agent setting file
  template:
    src: mackerel-agent.conf.j2
    dest: /etc/mackerel-agent/mackerel-agent.conf
  notify: restart mackerel-agent
- name: mackerel-agent is active and enabled on system startup
  service:
    name: mackerel-agent
    state: started
    enabled: yes
  when: mackerel_agent_active_and_enabled_on_system_startup
